version: '3'

services:
  app:
    build: .
    restart: on-failure
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:14.4-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres-todo-db:/var/lib/postgresql/data:cached

volumes:
  postgres-todo-db:
    driver: local